CREATE PROC FI_SP_IncBeneficiarioV2
    @NOME          VARCHAR (50) ,
	@CPF		   VARCHAR (11) ,
	@IdCliente	   BIGINT

AS
BEGIN
	INSERT INTO BENEFICIARIOS (CPF, NOME, IDCLIENTE) 
	VALUES (@CPF, @NOME, @IdCliente)

	SELECT SCOPE_IDENTITY()

END